### ISSUE TITLE
Issue #1: Email service not working

### ISSUE THREAD

**Issue by Ananta-Vaishnavi** [Peddinti-Sriram-Bharadwaj/peddinti-sriram-bharadwaj.github.io#1]
Issue: Getting error while sending a mail
![image](https://github.com/SriramBharadwaj1/srirambharadwaj1.github.io/assets/94735204/475cc27b-b409-454c-a41f-73ae33d5f033)
Browser Tested: Google, Brave

**Comment by Peddinti-Sriram-Bharadwaj** [comment]
will rectify. Thanks for notifying

**Comment by Peddinti-Sriram-Bharadwaj** [comment]
issue fixed with commit 8310b95
